version: "3.9"
services:
  web:
    # The `web` service uses an image that’s built from the Dockerfile in the current directory.
    build: .
    image: deploy-tomcat-war:1.0
    container_name: deploy-tomcat-war
    # restart: always

    # It then binds the container and the host machine to the exposed port, `5000`.
    # This example service uses the default port for the Flask web server, `5000`.
    ports:
      - "8080:8080"
    # The new `volumes` key mounts the project directory (current directory) on the host to `/code` inside the container,
    volumes:
      - "./volume/index.html:/usr/local/tomcat/webapps/examples/index.html"
    environment:
       APPLICATION_NAME: deploy-tomcat-war-docker-compose
