version: "3.9"
services:
  mysql8:
    image: mysql:8.0.23
    container_name: mysql-8.0.23
    ports:
      - 23306:3306
    volumes:
      - "D:/docker-volumes/db/mysql8/data/:/var/lib/mysql/"
      # container first start init-sql(`.sh`, `.sql` and `.sql.gz`).
      - "./mysql/:/docker-entrypoint-initdb.d/"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
#      MYSQL_DATABASE: nacos_v200