version: "3.9"
services:
  web:
    # The `web` service uses an image that’s built from the Dockerfile in the current directory.
    build: .
    image: docker-compose-web:v1.0
    # It then binds the container and the host machine to the exposed port, `5000`.
    # This example service uses the default port for the Flask web server, `5000`.
    ports:
      - "5000:5000"
  redis:
    # The `redis` service uses a public `Redis image` pulled from the Docker Hub registry.
    image: "redis:5.0.10"